vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '%app.path.books_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.books_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
